// <auto-generated />
using System;
using K9.Modules.Health.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace K9.Modules.Health.Persistence.Migrations
{
    [DbContext(typeof(HealthDbContext))]
    [Migration("20251125233618_InitialHealthStructure")]
    partial class InitialHealthStructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("health")
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("K9.Modules.Health.Domain.DogProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("DogProfiles", "health");
                });

            modelBuilder.Entity("K9.Modules.Health.Domain.VaccinationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateAdministered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DogProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VaccineName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("VetClinicName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("DogProfileId");

                    b.ToTable("VaccinationRecords", "health");
                });

            modelBuilder.Entity("K9.Modules.Health.Domain.WeightLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DogProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("MeasuredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Weight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("DogProfileId");

                    b.ToTable("WeightLogs", "health");
                });

            modelBuilder.Entity("K9.Modules.Health.Domain.VaccinationRecord", b =>
                {
                    b.HasOne("K9.Modules.Health.Domain.DogProfile", null)
                        .WithMany("Vaccinations")
                        .HasForeignKey("DogProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("K9.Modules.Health.Domain.WeightLog", b =>
                {
                    b.HasOne("K9.Modules.Health.Domain.DogProfile", null)
                        .WithMany("WeightLogs")
                        .HasForeignKey("DogProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("K9.Modules.Health.Domain.DogProfile", b =>
                {
                    b.Navigation("Vaccinations");

                    b.Navigation("WeightLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
